//! PostgreSQL Object Identifier (OID) constants and type name mappings.
//! Generated from PostgreSQL pg_type table (oids < 10000).

const std = @import("std");

/// OID is a PostgreSQL Object Identifier.
pub const Oid = u32;

// --- OID constants (T_* values) ---
// The names correspond to PostgreSQL's pg_type.typname.

pub const T_bool: Oid = 16;
pub const T_bytea: Oid = 17;
pub const T_char: Oid = 18;
pub const T_name: Oid = 19;
pub const T_int8: Oid = 20;
pub const T_int2: Oid = 21;
pub const T_int2vector: Oid = 22;
pub const T_int4: Oid = 23;
pub const T_regproc: Oid = 24;
pub const T_text: Oid = 25;
pub const T_oid: Oid = 26;
pub const T_tid: Oid = 27;
pub const T_xid: Oid = 28;
pub const T_cid: Oid = 29;
pub const T_oidvector: Oid = 30;
pub const T_pg_ddl_command: Oid = 32;
pub const T_pg_type: Oid = 71;
pub const T_pg_attribute: Oid = 75;
pub const T_pg_proc: Oid = 81;
pub const T_pg_class: Oid = 83;
pub const T_json: Oid = 114;
pub const T_xml: Oid = 142;
pub const T__xml: Oid = 143;
pub const T_pg_node_tree: Oid = 194;
pub const T__json: Oid = 199;
pub const T_smgr: Oid = 210;
pub const T_index_am_handler: Oid = 325;
pub const T_point: Oid = 600;
pub const T_lseg: Oid = 601;
pub const T_path: Oid = 602;
pub const T_box: Oid = 603;
pub const T_polygon: Oid = 604;
pub const T_line: Oid = 628;
pub const T__line: Oid = 629;
pub const T_cidr: Oid = 650;
pub const T__cidr: Oid = 651;
pub const T_float4: Oid = 700;
pub const T_float8: Oid = 701;
pub const T_abstime: Oid = 702;
pub const T_reltime: Oid = 703;
pub const T_tinterval: Oid = 704;
pub const T_unknown: Oid = 705;
pub const T_circle: Oid = 718;
pub const T__circle: Oid = 719;
pub const T_money: Oid = 790;
pub const T__money: Oid = 791;
pub const T_macaddr: Oid = 829;
pub const T_inet: Oid = 869;
pub const T__bool: Oid = 1000;
pub const T__bytea: Oid = 1001;
pub const T__char: Oid = 1002;
pub const T__name: Oid = 1003;
pub const T__int2: Oid = 1005;
pub const T__int2vector: Oid = 1006;
pub const T__int4: Oid = 1007;
pub const T__regproc: Oid = 1008;
pub const T__text: Oid = 1009;
pub const T__tid: Oid = 1010;
pub const T__xid: Oid = 1011;
pub const T__cid: Oid = 1012;
pub const T__oidvector: Oid = 1013;
pub const T__bpchar: Oid = 1014;
pub const T__varchar: Oid = 1015;
pub const T__int8: Oid = 1016;
pub const T__point: Oid = 1017;
pub const T__lseg: Oid = 1018;
pub const T__path: Oid = 1019;
pub const T__box: Oid = 1020;
pub const T__float4: Oid = 1021;
pub const T__float8: Oid = 1022;
pub const T__abstime: Oid = 1023;
pub const T__reltime: Oid = 1024;
pub const T__tinterval: Oid = 1025;
pub const T__polygon: Oid = 1027;
pub const T__oid: Oid = 1028;
pub const T_aclitem: Oid = 1033;
pub const T__aclitem: Oid = 1034;
pub const T__macaddr: Oid = 1040;
pub const T__inet: Oid = 1041;
pub const T_bpchar: Oid = 1042;
pub const T_varchar: Oid = 1043;
pub const T_date: Oid = 1082;
pub const T_time: Oid = 1083;
pub const T_timestamp: Oid = 1114;
pub const T__timestamp: Oid = 1115;
pub const T__date: Oid = 1182;
pub const T__time: Oid = 1183;
pub const T_timestamptz: Oid = 1184;
pub const T__timestamptz: Oid = 1185;
pub const T_interval: Oid = 1186;
pub const T__interval: Oid = 1187;
pub const T__numeric: Oid = 1231;
pub const T_pg_database: Oid = 1248;
pub const T__cstring: Oid = 1263;
pub const T_timetz: Oid = 1266;
pub const T__timetz: Oid = 1270;
pub const T_bit: Oid = 1560;
pub const T__bit: Oid = 1561;
pub const T_varbit: Oid = 1562;
pub const T__varbit: Oid = 1563;
pub const T_numeric: Oid = 1700;
pub const T_refcursor: Oid = 1790;
pub const T__refcursor: Oid = 2201;
pub const T_regprocedure: Oid = 2202;
pub const T_regoper: Oid = 2203;
pub const T_regoperator: Oid = 2204;
pub const T_regclass: Oid = 2205;
pub const T_regtype: Oid = 2206;
pub const T__regprocedure: Oid = 2207;
pub const T__regoper: Oid = 2208;
pub const T__regoperator: Oid = 2209;
pub const T__regclass: Oid = 2210;
pub const T__regtype: Oid = 2211;
pub const T_record: Oid = 2249;
pub const T_cstring: Oid = 2275;
pub const T_any: Oid = 2276;
pub const T_anyarray: Oid = 2277;
pub const T_void: Oid = 2278;
pub const T_trigger: Oid = 2279;
pub const T_language_handler: Oid = 2280;
pub const T_internal: Oid = 2281;
pub const T_opaque: Oid = 2282;
pub const T_anyelement: Oid = 2283;
pub const T__record: Oid = 2287;
pub const T_anynonarray: Oid = 2776;
pub const T_pg_authid: Oid = 2842;
pub const T_pg_auth_members: Oid = 2843;
pub const T__txid_snapshot: Oid = 2949;
pub const T_uuid: Oid = 2950;
pub const T__uuid: Oid = 2951;
pub const T_txid_snapshot: Oid = 2970;
pub const T_fdw_handler: Oid = 3115;
pub const T_pg_lsn: Oid = 3220;
pub const T__pg_lsn: Oid = 3221;
pub const T_tsm_handler: Oid = 3310;
pub const T_anyenum: Oid = 3500;
pub const T_tsvector: Oid = 3614;
pub const T_tsquery: Oid = 3615;
pub const T_gtsvector: Oid = 3642;
pub const T__tsvector: Oid = 3643;
pub const T__gtsvector: Oid = 3644;
pub const T__tsquery: Oid = 3645;
pub const T_regconfig: Oid = 3734;
pub const T__regconfig: Oid = 3735;
pub const T_regdictionary: Oid = 3769;
pub const T__regdictionary: Oid = 3770;
pub const T_jsonb: Oid = 3802;
pub const T__jsonb: Oid = 3807;
pub const T_anyrange: Oid = 3831;
pub const T_event_trigger: Oid = 3838;
pub const T_int4range: Oid = 3904;
pub const T__int4range: Oid = 3905;
pub const T_numrange: Oid = 3906;
pub const T__numrange: Oid = 3907;
pub const T_tsrange: Oid = 3908;
pub const T__tsrange: Oid = 3909;
pub const T_tstzrange: Oid = 3910;
pub const T__tstzrange: Oid = 3911;
pub const T_daterange: Oid = 3912;
pub const T__daterange: Oid = 3913;
pub const T_int8range: Oid = 3926;
pub const T__int8range: Oid = 3927;
pub const T_pg_shseclabel: Oid = 4066;
pub const T_regnamespace: Oid = 4089;
pub const T__regnamespace: Oid = 4090;
pub const T_regrole: Oid = 4096;
pub const T__regrole: Oid = 4097;

/// Maximum OID value present in the constants (inclusive).
pub const max_oid = 4097;

/// Lookup table mapping OID to its PostgreSQL type name (uppercase).
/// Use `typeName(oid)` to get the name, or access this array directly.
/// Indexes with no known type contain `null`.
pub const type_names: [max_oid + 1]?[]const u8 = blk: {
    var arr: [max_oid + 1]?[]const u8 = .{null} ** (max_oid + 1);
    arr[T_bool] = "BOOL";
    arr[T_bytea] = "BYTEA";
    arr[T_char] = "CHAR";
    arr[T_name] = "NAME";
    arr[T_int8] = "INT8";
    arr[T_int2] = "INT2";
    arr[T_int2vector] = "INT2VECTOR";
    arr[T_int4] = "INT4";
    arr[T_regproc] = "REGPROC";
    arr[T_text] = "TEXT";
    arr[T_oid] = "OID";
    arr[T_tid] = "TID";
    arr[T_xid] = "XID";
    arr[T_cid] = "CID";
    arr[T_oidvector] = "OIDVECTOR";
    arr[T_pg_ddl_command] = "PG_DDL_COMMAND";
    arr[T_pg_type] = "PG_TYPE";
    arr[T_pg_attribute] = "PG_ATTRIBUTE";
    arr[T_pg_proc] = "PG_PROC";
    arr[T_pg_class] = "PG_CLASS";
    arr[T_json] = "JSON";
    arr[T_xml] = "XML";
    arr[T__xml] = "_XML";
    arr[T_pg_node_tree] = "PG_NODE_TREE";
    arr[T__json] = "_JSON";
    arr[T_smgr] = "SMGR";
    arr[T_index_am_handler] = "INDEX_AM_HANDLER";
    arr[T_point] = "POINT";
    arr[T_lseg] = "LSEG";
    arr[T_path] = "PATH";
    arr[T_box] = "BOX";
    arr[T_polygon] = "POLYGON";
    arr[T_line] = "LINE";
    arr[T__line] = "_LINE";
    arr[T_cidr] = "CIDR";
    arr[T__cidr] = "_CIDR";
    arr[T_float4] = "FLOAT4";
    arr[T_float8] = "FLOAT8";
    arr[T_abstime] = "ABSTIME";
    arr[T_reltime] = "RELTIME";
    arr[T_tinterval] = "TINTERVAL";
    arr[T_unknown] = "UNKNOWN";
    arr[T_circle] = "CIRCLE";
    arr[T__circle] = "_CIRCLE";
    arr[T_money] = "MONEY";
    arr[T__money] = "_MONEY";
    arr[T_macaddr] = "MACADDR";
    arr[T_inet] = "INET";
    arr[T__bool] = "_BOOL";
    arr[T__bytea] = "_BYTEA";
    arr[T__char] = "_CHAR";
    arr[T__name] = "_NAME";
    arr[T__int2] = "_INT2";
    arr[T__int2vector] = "_INT2VECTOR";
    arr[T__int4] = "_INT4";
    arr[T__regproc] = "_REGPROC";
    arr[T__text] = "_TEXT";
    arr[T__tid] = "_TID";
    arr[T__xid] = "_XID";
    arr[T__cid] = "_CID";
    arr[T__oidvector] = "_OIDVECTOR";
    arr[T__bpchar] = "_BPCHAR";
    arr[T__varchar] = "_VARCHAR";
    arr[T__int8] = "_INT8";
    arr[T__point] = "_POINT";
    arr[T__lseg] = "_LSEG";
    arr[T__path] = "_PATH";
    arr[T__box] = "_BOX";
    arr[T__float4] = "_FLOAT4";
    arr[T__float8] = "_FLOAT8";
    arr[T__abstime] = "_ABSTIME";
    arr[T__reltime] = "_RELTIME";
    arr[T__tinterval] = "_TINTERVAL";
    arr[T__polygon] = "_POLYGON";
    arr[T__oid] = "_OID";
    arr[T_aclitem] = "ACLITEM";
    arr[T__aclitem] = "_ACLITEM";
    arr[T__macaddr] = "_MACADDR";
    arr[T__inet] = "_INET";
    arr[T_bpchar] = "BPCHAR";
    arr[T_varchar] = "VARCHAR";
    arr[T_date] = "DATE";
    arr[T_time] = "TIME";
    arr[T_timestamp] = "TIMESTAMP";
    arr[T__timestamp] = "_TIMESTAMP";
    arr[T__date] = "_DATE";
    arr[T__time] = "_TIME";
    arr[T_timestamptz] = "TIMESTAMPTZ";
    arr[T__timestamptz] = "_TIMESTAMPTZ";
    arr[T_interval] = "INTERVAL";
    arr[T__interval] = "_INTERVAL";
    arr[T__numeric] = "_NUMERIC";
    arr[T_pg_database] = "PG_DATABASE";
    arr[T__cstring] = "_CSTRING";
    arr[T_timetz] = "TIMETZ";
    arr[T__timetz] = "_TIMETZ";
    arr[T_bit] = "BIT";
    arr[T__bit] = "_BIT";
    arr[T_varbit] = "VARBIT";
    arr[T__varbit] = "_VARBIT";
    arr[T_numeric] = "NUMERIC";
    arr[T_refcursor] = "REFCURSOR";
    arr[T__refcursor] = "_REFCURSOR";
    arr[T_regprocedure] = "REGPROCEDURE";
    arr[T_regoper] = "REGOPER";
    arr[T_regoperator] = "REGOPERATOR";
    arr[T_regclass] = "REGCLASS";
    arr[T_regtype] = "REGTYPE";
    arr[T__regprocedure] = "_REGPROCEDURE";
    arr[T__regoper] = "_REGOPER";
    arr[T__regoperator] = "_REGOPERATOR";
    arr[T__regclass] = "_REGCLASS";
    arr[T__regtype] = "_REGTYPE";
    arr[T_record] = "RECORD";
    arr[T_cstring] = "CSTRING";
    arr[T_any] = "ANY";
    arr[T_anyarray] = "ANYARRAY";
    arr[T_void] = "VOID";
    arr[T_trigger] = "TRIGGER";
    arr[T_language_handler] = "LANGUAGE_HANDLER";
    arr[T_internal] = "INTERNAL";
    arr[T_opaque] = "OPAQUE";
    arr[T_anyelement] = "ANYELEMENT";
    arr[T__record] = "_RECORD";
    arr[T_anynonarray] = "ANYNONARRAY";
    arr[T_pg_authid] = "PG_AUTHID";
    arr[T_pg_auth_members] = "PG_AUTH_MEMBERS";
    arr[T__txid_snapshot] = "_TXID_SNAPSHOT";
    arr[T_uuid] = "UUID";
    arr[T__uuid] = "_UUID";
    arr[T_txid_snapshot] = "TXID_SNAPSHOT";
    arr[T_fdw_handler] = "FDW_HANDLER";
    arr[T_pg_lsn] = "PG_LSN";
    arr[T__pg_lsn] = "_PG_LSN";
    arr[T_tsm_handler] = "TSM_HANDLER";
    arr[T_anyenum] = "ANYENUM";
    arr[T_tsvector] = "TSVECTOR";
    arr[T_tsquery] = "TSQUERY";
    arr[T_gtsvector] = "GTSVECTOR";
    arr[T__tsvector] = "_TSVECTOR";
    arr[T__gtsvector] = "_GTSVECTOR";
    arr[T__tsquery] = "_TSQUERY";
    arr[T_regconfig] = "REGCONFIG";
    arr[T__regconfig] = "_REGCONFIG";
    arr[T_regdictionary] = "REGDICTIONARY";
    arr[T__regdictionary] = "_REGDICTIONARY";
    arr[T_jsonb] = "JSONB";
    arr[T__jsonb] = "_JSONB";
    arr[T_anyrange] = "ANYRANGE";
    arr[T_event_trigger] = "EVENT_TRIGGER";
    arr[T_int4range] = "INT4RANGE";
    arr[T__int4range] = "_INT4RANGE";
    arr[T_numrange] = "NUMRANGE";
    arr[T__numrange] = "_NUMRANGE";
    arr[T_tsrange] = "TSRANGE";
    arr[T__tsrange] = "_TSRANGE";
    arr[T_tstzrange] = "TSTZRANGE";
    arr[T__tstzrange] = "_TSTZRANGE";
    arr[T_daterange] = "DATERANGE";
    arr[T__daterange] = "_DATERANGE";
    arr[T_int8range] = "INT8RANGE";
    arr[T__int8range] = "_INT8RANGE";
    arr[T_pg_shseclabel] = "PG_SHSECLABEL";
    arr[T_regnamespace] = "REGNAMESPACE";
    arr[T__regnamespace] = "_REGNAMESPACE";
    arr[T_regrole] = "REGROLE";
    arr[T__regrole] = "_REGROLE";
    break :blk arr;
};

/// Returns the PostgreSQL type name for the given OID, or `null` if unknown.
pub fn typeName(oid: Oid) ?[]const u8 {
    if (oid > max_oid) return null;
    return type_names[@as(usize, @intCast(oid))];
}

// --- Tests ---
const testing = std.testing;

test "lookup known OID" {
    try testing.expectEqualStrings("BOOL", typeName(T_bool).?);
    try testing.expectEqualStrings("INT4", typeName(T_int4).?);
    try testing.expectEqualStrings("TEXT", typeName(T_text).?);
}

test "lookup unknown OID" {
    try testing.expect(typeName(9999) == null);
    try testing.expect(typeName(0) == null);
}

test "array indexing matches constants" {
    try testing.expect(type_names[T_bool] != null);
    try testing.expect(type_names[T_text] != null);
}
